### ISSUE TITLE
Properly Linking to Leigh

### ISSUE THREAD

**Issue by LSheneman** [dib-lab/literate-resting#3]
@ctb I plan on posting the base of literate-resting on my github, and will be expanding for my own needs (thus under a personal CC license). I believe the best way is to re-base such that GED-lab is a branch of my repo. 

You guys are still welcome to use it, of course. Let me know how I can assist in the transfer.

**Comment by drtamermansour** [comment]
I cloned literate-resting to my local disk. I had to change the "End of Line" mode from windows (\r\n) to unix (\n) to get it run.

**Comment by ctb** [comment]
On Sat, Jan 31, 2015 at 07:02:25PM -0800, Tamer Mansour wrote:
> I cloned literate-resting to my local disk. I had to change the "End of Line" mode from windows (\r\n) to unix (\n) to get it run.

Sorry, I don't understand - are you running on Windows or Linux or Mac?

--t

**Comment by drtamermansour** [comment]
I am using cygwin on windows

**Comment by ctb** [comment]
OK.  I wouldn't do that if I were you... many problems will simply be
caused by Windows, which we don't support at all (khmer, too).

On Sat, Jan 31, 2015 at 07:27:28PM -0800, Tamer Mansour wrote:
> I am using cygwin on windows
> 
> On Sat, Jan 31, 2015 at 9:11 PM, C. Titus Brown <notifications@github.com>
> wrote:
> 
> > On Sat, Jan 31, 2015 at 07:02:25PM -0800, Tamer Mansour wrote:
> > > I cloned literate-resting to my local disk. I had to change the "End of
> > Line" mode from windows (\r\n) to unix (\n) to get it run.
> >
> > Sorry, I don't understand - are you running on Windows or Linux or Mac?
> >
> > --t
> >
> > ???
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ged-lab/literate-resting/issues/3#issuecomment-72349181>
> > .
> >
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ged-lab/literate-resting/issues/3#issuecomment-72349582
-- 
C. Titus Brown, ctbrown@ucdavis.edu
